function [varargout] = ode(varargin)
  argout_0 = cell(3,1);
  w0 = varargin{2};
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w1 = in_flat(nonzeros(1:1:1));
  w1 = sparse(sp_i, sp_j, w1, sp_m, sp_n);
  w2 = varargin{3};
  w3 = w2.^2;
  w1 = w1*w3;
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(2:1:2));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w3 = w3*w2;
  w1 = (w1+w3);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(3:1:3));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w1 = (w1+w3);
  w4 = varargin{1};
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 3;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1];
  sp_in_i = [1, 2, 3];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w4(sp_in==1);
  w3 = in_flat(nonzeros(3:1:3));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w3 = cos(w3);
  w1 = w1*w3;
  sp_in_m = 1;
  sp_in_n = 1;
  sp_in_j = [1];
  sp_in_i = [1];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  argout_0{1} = w1(sp_in==1);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w1 = in_flat(nonzeros(1:1:1));
  w1 = sparse(sp_i, sp_j, w1, sp_m, sp_n);
  w3 = w2.^2;
  w1 = w1*w3;
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(2:1:2));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w3 = w3*w2;
  w1 = (w1+w3);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(3:1:3));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w1 = (w1+w3);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 3;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1];
  sp_in_i = [1, 2, 3];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w4(sp_in==1);
  w3 = in_flat(nonzeros(3:1:3));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w3 = sin(w3);
  w1 = w1*w3;
  sp_in_m = 1;
  sp_in_n = 1;
  sp_in_j = [1];
  sp_in_i = [1];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  argout_0{2} = w1(sp_in==1);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w1 = in_flat(nonzeros(4:1:4));
  w1 = sparse(sp_i, sp_j, w1, sp_m, sp_n);
  m = 3.0000000000000000e+00;
  w3 = m;
  w3 = w2.^w3;
  w1 = w1*w3;
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(5:1:5));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w5 = w2.^2;
  w3 = w3*w5;
  w1 = (w1+w3);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(6:1:6));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w3 = w3*w2;
  w1 = (w1+w3);
  sp_m = 1;
  sp_n = 1;
  sp_j = [1];
  sp_i = [1];
  sp_in_m = 7;
  sp_in_n = 1;
  sp_in_j = [1, 1, 1, 1, 1, 1, 1];
  sp_in_i = [1, 2, 3, 4, 5, 6, 7];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  in_flat = w0(sp_in==1);
  w3 = in_flat(nonzeros(7:1:7));
  w3 = sparse(sp_i, sp_j, w3, sp_m, sp_n);
  w1 = (w1+w3);
  sp_in_m = 1;
  sp_in_n = 1;
  sp_in_j = [1];
  sp_in_i = [1];
  sp_in = sparse(sp_in_i, sp_in_j, ones(size(sp_in_i)), sp_in_m, sp_in_n);
  argout_0{3} = w1(sp_in==1);
  varargout{1} = reshape(vertcat(argout_0{:}), 3, 1);
end
function y=nonzeros_gen(x)
  if isa(x,'casadi.SX') || isa(x,'casadi.MX') || isa(x,'casadi.DM')
    y = x{:};
  elseif isa(x,'sdpvar')
    b = getbase(x);
    f = find(sum(b~=0,2));
    y = sdpvar(length(f),1,[],getvariables(x),b(f,:));
  else
    y = nonzeros(x);
  end
end
function y=if_else_zero_gen(c,e)
  if isa(c+e,'casadi.SX') || isa(c+e,'casadi.MX') || isa(c+e,'casadi.DM')
    y = if_else(c, e, 0);
  else
    if c
        y = x;
    else
        y = 0;
    end
  end
end
